
exports.negativeGhostRider = [
    "Ever told on a nigga",
    "Ever set a nigga up",
    "You a sap",
    "Let me hold a couple dollars",
    "Stock rims on a scraper",
    "Poodle in my blood",
    "You a loser",
    "You still sell dope",
    "Got a little gouda",
    "You in love wit' the ho",
    "You gon' cry if she leave",
    "Starving",
    
    "Lazy",
    "Hater",
    "Traitor",
    "Sleep",
    "Scared of the dark",
    "Narc",
    "Gossip like a broad",
    "Slippin",
    "Sober as a gopher",
    "Star Wars",
    "Never leave the house without my strap",
    "Never been a sucka or a pussy",

    "Was it love at first sight",
    "Was it ripe",
    "Got some property",
    "You softer than a sock",
    "Slow",
    "Your team weak",
    "Shallow",
    "Broke",
    "Not a BB or a pellet gun",
    "If I get into it will run",
    "Still live in the trap",
    "Wear a wire and a camera",
].map(s => s.toLowerCase())

exports.affirmative = [
    "Ever squeezed a trigger",
    "Ever helped a brother out when he was down on his luck",
    "You a boss player, you a mack",
    "Y'all still be poppin' y'all collars",
    "Paint wetter than a lake",
    "Bitch, I'm a thug",
    "Winner",
    "Dinner",
    "Now you cleaner than a bar of Dove soap",
    "Got a thumper, got a Ruger",
    "She bringin' you the dough",
    "You gon' fly overseas",
    
    "Got dick that'll drive a ho crazy",
    "Wanna see a player get paper",
    "Loyal to my soil, not a faker",
    "Bust moves, hella active in the streets",
    "Have money, have heart",
    "Shark",
    "Check a bitch like a smog",
    "Trippin",
    "Higher than a rollercoaster",
    "Yoda",
    "Shoot a muthafucka in his nap",
    "Blowin' cookie, never coughin' like a rookie",

    "Did she ride you like a bike",
    "Was her pussy tight",
    "Drive a Maserati",
    "You solid as a rock",
    "Trained to go",
    "You respected in the stree-neets",
    "Di-neep",
    "Chi-neat",
    "But a long barrel base drum",
    "I'mma give a nigga fair one",
    "You ever go back",
    "Ears to the scanner",
].map(s => s.toLowerCase())