
exports.negativeGhostRiderRegex = [
    /ev(er|a) told on a nigga/,
    /ev(er|a) set a nigga up/,
    /you a sap/,
    /(let me|lemme) hold a coup(le|a) doll(ars|as)/,
    /stock rims on a scraper/,
    /poodle in my blood/,
    /(you )?a los(er|a)/,
    /(you )?still (sell|sellin) dope/,
    /Got a little gouda/,
    /(you )?in love (wit'|wit|with) the ho/,
    /(you )?(gon'|gonna|going to) cry if she (leave|leaves)/,
    /(starving|starvin)/,
    
    /lazy/,
    /(hater|hata)/,
    /traitor/,
    /(sleep|shleep)/,
    /scared of the dark/,
    /narc/,
    /gossip like a broad/,
    /slippin/,
    /sober as a gopher/,
    /star wars/,
    /(never|neva|ever|eva) leave (the|da) house without (my|your|ur) strap/,
    /(never|neva) been a (sucka|sucker) or a pussy/,

    /was it love at first sight/,
    /was it ripe/,
    /got some property/,
    /(you )?softer than a sock/,
    /slow/,
    /(your )?team weak/,
    /shallow/,
    /broke/,
    /(not a )?bb or a pellet gun/,
    /if (i|you) get into it will run/,
    /(still )?live in the trap/,
    /wear a wire and a camera/,
]

exports.affirmativeRegex = [
    /(ever|eva) squeezed a trigger/,
    /(ever|eva) helped a brother out when he was down on his luck/,
    /(you )?a boss player, you a mack/,
    /(y'all\s|yall\s)?still be (poppin'?|popping) (y'all|yall) collar?s/,
    /paint wetter than a lake/,
    /(bitch(,)?\s)?((i'm|im) a\s|ima\s)thug/,
    /winn(er|a)/,
    /dinn(er|a)/,
    /(now )?(you )?clean(er|a) than a bar of dove soap/,
    /(got a|gotta) thumper,? (got a|gotta) ruger/,
    /she (bringin'?|bringing) you the dough/,
    /(you )?(gon'?|gonna) fly overseas/,
    
    /got dick that'?ll drive a (ho|hoe) crazy/,
    /(wanna|want to) see a player get paper/,
    /loyal to (my|your|ur) soil,? not a fak(er|a)/,
    /bust moves,? hella active in the streets/,
    /have money,? have heart/,
    /shark/,
    /check a bitch like a smog/,
    /tripp(in'?|ing)/,
    /high(er|a) than a rollercoaster/,
    /yoda/,
    /shoot a muthafuck(a|er) in his nap/,
    /blowin'? cookie,? never coughin' like a rookie/,

    /(did )?she ride you like a bike/,
    /was her pussy tight/,
    /drive a maserati/,
    /(you )?solid as a rock/,
    /trained to go/,
    /(you )?respected in the (stree-neets|streets)/,
    /di(-|\s)?neep/,
    /chi(-|\s)?neat/,
    /(but )?(a )?long barrel base drum/,
    /(i'?m?ma\s)?give a nigga fair one/,
    /(you )?ev(er|a) go back/,
    /ears to the scanner/,
]

exports.negativeGhostRider = [
    "Ever told on a nigga",
    "Ever set a nigga up",
    "You a sap",
    "Let me hold a couple dollars",
    "Stock rims on a scraper",
    "Poodle in my blood",
    "You a loser",
    "You still sell dope",
    "Got a little gouda",
    "You in love wit' the ho",
    "You gon' cry if she leave",
    "Starving",
    
    "Lazy",
    "Hater",
    "Traitor",
    "Sleep",
    "Scared of the dark",
    "Narc",
    "Gossip like a broad",
    "Slippin",
    "Sober as a gopher",
    "Star Wars",
    "Never leave the house without my strap",
    "Never been a sucka or a pussy",

    "Was it love at first sight",
    "Was it ripe",
    "Got some property",
    "You softer than a sock",
    "Slow",
    "Your team weak",
    "Shallow",
    "Broke",
    "Not a BB or a pellet gun",
    "If I get into it will run",
    "Still live in the trap",
    "Wear a wire and a camera",
].map(s => s.toLowerCase())

exports.affirmative = [
    "Ever squeezed a trigger",
    "Ever helped a brother out when he was down on his luck",
    "You a boss player, you a mack",
    "Y'all still be poppin' y'all collars",
    "Paint wetter than a lake",
    "Bitch, I'm a thug",
    "Winner",
    "Dinner",
    "Now you cleaner than a bar of Dove soap",
    "Got a thumper, got a Ruger",
    "She bringin' you the dough",
    "You gon' fly overseas",
    
    "Got dick that'll drive a ho crazy",
    "Wanna see a player get paper",
    "Loyal to my soil, not a faker",
    "Bust moves, hella active in the streets",
    "Have money, have heart",
    "Shark",
    "Check a bitch like a smog",
    "Trippin",
    "Higher than a rollercoaster",
    "Yoda",
    "Shoot a muthafucka in his nap",
    "Blowin' cookie, never coughin' like a rookie",

    "Did she ride you like a bike",
    "Was her pussy tight",
    "Drive a Maserati",
    "You solid as a rock",
    "Trained to go",
    "You respected in the stree-neets",
    "Di-neep",
    "Chi-neat",
    "But a long barrel base drum",
    "I'mma give a nigga fair one",
    "You ever go back",
    "Ears to the scanner",
].map(s => s.toLowerCase())